# Generated by Django 5.1 on 2024-08-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_amenity_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
