name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
    
jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@main
      if: env.previous_tag
      with:
        test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

  tag_test:
    runs-on: ubuntu-latest
    steps:
    - name: Any Name bash test
      shell: bash
      run: |
        echo "version - ${{ steps.create_tag.outputs.version }}"
        echo "version || preversion - ${{ steps.create_tag.outputs.version || steps.create_tag.outputs.preversion }}"
        echo "versionNumber - ${{ steps.create_tag.outputs.versionNumber }}"
        echo "versionNumber || preversionNumber - ${{ steps.create_tag.outputs.versionNumber || steps.create_tag.outputs.preversionNumber }}"
        echo "majorVersion - ${{ steps.create_tag.outputs.majorVersion }}"
        echo "minorVersion - ${{ steps.create_tag.outputs.minorVersion }}"
        echo "patchVersion - ${{ steps.create_tag.outputs.patchVersion }}"
        echo "preversion - ${{ steps.create_tag.outputs.preversion }}"
        echo "successful - ${{ steps.create_tag.outputs.successful }}"
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:${{ github.sha }}
