name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

env:
  MAJOR: ${{ vars.MAJOR }} # 1
  MINOR: ${{ vars.MINOR }} # 1

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
    - name: version update
      uses: action-pack/set-variable@v1
      with:
        name: 'MINOR'
        value: ${{ env.MINOR }} + 1
        token: ${{ secrets.GITHUB_TOKEN }}
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout 
  #     uses: actions/checkout@v4
    
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v3
    
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
    
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    
  #   - name: Build and push
  #     uses: docker/build-push-action@v6
  #     with:
  #       context: .
  #       push: true
  #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:${{ github.sha }}
