name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set short git commit SHA
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 6
    
    - name: Set environment variable
      uses: alsosee/envset@v1
      with:
        name: SHA
        value: ${{ steps.short-sha.outputs.sha }}
    # - run: echo $SHA
    #   env:
    #     SHA: ${{ steps.short-sha.outputs.sha }}
    
    # - name: Checkout 
    #   uses: actions/checkout@v4
    
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:${{ env.SHA }}
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: echo sha
      run: echo "sha = ${{env.SHA}}"