name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

env:
  GIT_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
  TARGET_REPOSITORY: ${{ vars.DEVOPS_REPOSITORY }}
  

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      SHA: ${{ env.SHA }}
    steps:
    - name: Set short git commit SHA
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env:
        SHA: ${{ steps.short-sha.outputs.sha }}
    - name: set variables
      uses: marcdomain/set-variables@v1.2
      with:
        variables: |
          SHA: "${{ env.SHA }}"
    
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:${{ env.SHA }}
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout ${{ env.TARGET_REPOSITORY }}  repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.TARGET_REPOSITORY }}
        token: ${{ env.GIT_TOKEN }}
        path: helm-repository

    - run: ls -al

    - uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'helm-repository/apps/airbnb-server/values.yaml'
        propertyPath: 'image.tag'
        value: ${{ needs.build.outputs.SHA }}
        message: 'ci: Update image tag to ${{ needs.build.outputs.SHA }}'
        commitChange: true
        branch: main
        repository: ${{ env.TARGET_REPOSITORY }}
        token: ${{ env.GIT_TOKEN }}