name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
    
jobs:
  Job1:
    runs-on: ubuntu-latest
    name: Job to evaluate variables
    outputs:
      ENVIRONMENT: "environ-test"
      USER: "environ-user"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set variables
        uses: marcdomain/set-variables@v1.2
        with:
          variables: |
            ENVIRONMENT: "zzzzzz"
            USERNAME: "kkkkk"
      
      - name: Verify the variables
        run: |
          echo "environment is ${{ env.ENVIRONMENT }}"
          echo "username is ${{ env.USERNAME }}"

  Job2:
    runs-on: ubuntu-latest
    name: Use variables from previous job
    needs: Job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the output variables
        run: |
          echo "check the USERNAME ${{ needs.Job1.outputs.USER }}"
          echo "check the ENVIRON ${{ needs.Job1.outputs.ENVIRONMENT }}"
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout 
  #     uses: actions/checkout@v4
    
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v3
    
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
    
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    
  #   - name: Build and push
  #     uses: docker/build-push-action@v6
  #     with:
  #       context: .
  #       push: true
  #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}:${{ github.sha }}
